name: whatsapp_sender
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+13

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  permission_handler: ^3.0.0
  contacts_service: ^0.3.10
  clipboard: ^0.1.2+8
  country_list_pick: ^1.0.1+2
  share: ^0.5.3
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  firebase_database: ^3.1.6
  url_launcher: ^5.7.2
  provider: ^4.0.5+1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_app.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo_app.png
    - assets/share.png